server:
  port: 8100
domain: 
  aastockAuth: http://www.aastocks.com/tc/resources/datafeed/getcetoken.ashx 
  
spring:
  datasource:
    #driverClassName: "org.hibernate.dialect.PostgreSQLDialect"
    driverClassName: org.postgresql.Driver
    #url: "jdbc:postgresql://localhost:5432/${database.postgres}"
    url: jdbc:postgresql://localhost:5432/wingon_pbs_data
    username: postgres
    password: admin1234
  jpa:
    #properties.hibernate.dialect: org.hibernate.dialect.PostgreSQLDiale
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update # update / create  or create-drop if you want to drop the tables on application shutdown
aastock:
  url: http://fctdata.aastocks.com/g2ce/Quote/getQuote?format=json
  referer: http://www.aastocks.com/
  #referer: http://www.aastocks.com/tc/usq/default.aspx
  auth: gC0PS6Fvshs9oUFAv/NT9CCgXpbvsUGVWI3JBR9tPIec0x6qqWGgNGbIgLQ1ZZAo8AXkVr390ox/QdGXJ6dHqI9Z3HCDsiyMzFu7ZhpBUnmr5UPeFmO3bPQ8oQ8dongrMJa8FFUIGKhtjN/mI3xBOIL+VkVNN3kW3QLCsmbezppm/q0JDuuV9o2mWWXtjCACyaDkxohirAaxuwHDsVUmCXigiYU9eLFY8QScsL3l031LHqkWv8fuMlr3cdAbOLbN3ClJ6C9xC+X5NpxeAGG4hpCfXllY7eua1jbJo6ZgA/sGuO2AbbKm2hn1zlme7NJGnkH4F35z9FdXQkbEiJce+Q==
  authUrl: http://www.aastocks.com/tc/resources/datafeed/getapitoken.ashx?PageURL=http%3A%2F%2Fwww.aastocks.com%2F&HKT=Y&UST=Y